name: Tests
on: [ push ]
env:
  PRICE_API_KEY: ${{ secrets.price_api_key }}
  SPRING_DATASOURCE_PASSWORD: ${{ secrets.spring_datasource_password }}
  SPRING_REDIS_PASSWORD: ${{ secrets.spring_redis_password }}
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Checkout badges branch to a badges directory nested inside first checkout
      uses: actions/checkout@v3
      with:
        ref: badges
        path: badges
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.8.4
    - name: Run tests
      run: mvn clean verify
