name: Tests
on: [ push ]
env:
  PRICE_API_KEY: ${{ secrets.price_api_key }}
  SPRING_DATASOURCE_PASSWORD: ${{ secrets.spring_datasource_password }}
  SPRING_REDIS_PASSWORD: ${{ secrets.spring_redis_password }}
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.8.4
    - name: Run tests
      run: mvn clean verify
    - name: Generate coverage badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-coverage-badge: true
    - name: Upload coverage badge to DigitalOcean bucket
      uses: BetaHuhn/do-spaces-action@v2
      with:
        access_key: ${{ secrets.BUCKET_ACCESS_KEY }}
        secret_key: ${{ secrets.BUCKET_SECRET_KEY }}
        space_name: visavttppaf-alfred
        space_region: sgp1
        source: .github/badges/jacoco.svg
        out_dir: coverage/${{ github.event.repository.name }}
        permission: public-read
    - name: Upload coverage report to DigitalOcean bucket
      uses: BetaHuhn/do-spaces-action@v2
      with:
        access_key: ${{ secrets.BUCKET_ACCESS_KEY }}
        secret_key: ${{ secrets.BUCKET_SECRET_KEY }}
        space_name: visavttppaf-alfred
        space_region: sgp1
        source: target/site/jacoco/
        out_dir: coverage/${{ github.event.repository.name }}/jacoco/
        permission: public-read
