name: versioned
on: 
  push:
    tags:
      - 'v*'
      - 'v*-alpha'
jobs:
  compile-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.8.4
    - name: Run tests
      run: mvn clean verify
    - name: Upload coverage badge to DigitalOcean bucket
      uses: BetaHuhn/do-spaces-action@v2
      with:
        access_key: ${{ secrets.BUCKET_ACCESS_KEY }}
        secret_key: ${{ secrets.BUCKET_SECRET_KEY }}
        space_name: visavttppaf-alfred
        space_region: sgp1
        source: .github/badges/jacoco.svg
        out_dir: coverage/${{ github.event.repository.name }}
        permission: public-read
    - name: Upload coverage report to DigitalOcean bucket
      uses: BetaHuhn/do-spaces-action@v2
      with:
        access_key: ${{ secrets.BUCKET_ACCESS_KEY }}
        secret_key: ${{ secrets.BUCKET_SECRET_KEY }}
        space_name: visavttppaf-alfred
        space_region: sgp1
        source: target/site/jacoco/
        out_dir: coverage/${{ github.event.repository.name }}/jacoco/
        permission: public-read
    - name: deploy to heroku
      uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "paf-assessment-alfred"
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        branch: ${{github.ref_name}}
  

